name: sfdx-validation-on-PR
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  sfdx-validation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout scm
        uses: actions/checkout@v4
      - name: Install node js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - run: |
          node --version
          npm --version
      - name: Install salesforce cli
        run: |
          wget https://developer.salesforce.com/media/salesforce-cli/sf/channels/stable/sf-linux-x64.tar.xz
          echo "present working directory is -----------------------"
          pwd
          mkdir -p ~/cli/sf
          tar xJf sf-linux-x64.tar.xz -C ~/cli/sf --strip-components 1
          echo "export PATH=~/cli/sf/bin:\$PATH" >> $HOME/.bash_profile
          source $HOME/.bash_profile
          sf --version
      - name: Install sfdx git delta plugin
        run: echo y | sfdx plugins:install sfdx-git-delta
