name: Manual Trigger Workflow

# Configure Manual Trigger
on:
  workflow_dispatch:
    inputs:
      source-branch:
        description: 'Name of the source branch'
        required: true
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Print source and target branch names
      run: |
        GITHUB_REF=${{ github.ref }}
        BRANCH_NAME=${GITHUB_REF##*/}
        echo "BASE_BRANCH_NAME=${BRANCH_NAME}" >> $GITHUB_ENV
        echo "BASE_BRANCH_COPY=${BRANCH_NAME}-copy" >> $GITHUB_ENV
        echo ${{ inputs.source-branch }}
    - name: Checkout scm
      uses: actions/checkout@v4
      with:
          fetch-depth: 0
    - name: Send Email
      uses: dawidd6/action-send-mail@v2
      with:
        server_address: smtp.office365.com
        server_port: 587
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: Your Email Subject
        body: |
          Hello,

          This is the body of your email.

          Regards,
          Your Name
        to: pratima.maiti77@gmail.com
        from: testing selenium
