name: Manual Trigger Workflow

# Configure Manual Trigger
on:
  workflow_dispatch:
    inputs:
      source-branch:
        description: 'Name of the source branch'
        required: true
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Print source and target branch names
      run: |
        GITHUB_REF=${{ github.ref }}
        BRANCH_NAME=${GITHUB_REF##*/}
        echo ${BRANCH_NAME}
        echo ${{ inputs.source-branch }}
    - name: Checkout scm
      uses: actions/checkout@v4
      with:
          fetch-depth: 0
    - name: Merge branch
      uses: everlytic/branch-merge@1.1.2
      with:
        github_token: ${{ github.token }}
        source_ref: ${{ github.ref }}
        target_branch: ${BRANCH_NAME}
        commit_message_template: '[Automated] Merged {source_ref} into target {target_branch}'
