name: Manual Trigger Workflow

# Configure Manual Trigger
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Merge source branch into Target branch
      run: |
        GITHUB_REF=${{ github.ref }}
        BRANCH_NAME=${GITHUB_REF##*/}
        echo ${BRANCH_NAME}
