name: Manual Trigger Workflow

# Configure Manual Trigger
on:
  workflow_dispatch:
    inputs:
      source-branch:
        description: 'Name of the source branch'
        required: true
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Print source and target branch names
      run: |
        GITHUB_REF=${{ github.ref }}
        BRANCH_NAME=${GITHUB_REF##*/}
        echo "BASE_BRANCH_NAME=${BRANCH_NAME}" >> $GITHUB_ENV
        echo ${{ inputs.source-branch }}
    - name: Checkout scm
      uses: actions/checkout@v4
      with:
          fetch-depth: 0
    - name: Merge Source into target
      run: |
        set -x
        git config --global user.email "pratima.maiti77@gmail.com"
        git config --global user.name "pratimamaiti13"
        git checkout ${{ env.BASE_BRANCH_NAME }}
        git merge --no-commit origin/${{ inputs.source-branch }} || true
        conflicted_files=$(git diff --name-only --diff-filter=U)
        git add .
        git commit -m "Merged ${{ inputs.source-branch }} into ${{ env.BASE_BRANCH_NAME }} with conflicts in: $conflicted_files"
        git push origin "${{ env.BASE_BRANCH_NAME }}"
