name: Manual Trigger Workflow

# Configure Manual Trigger
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Merge source branch into Target branch
      run: |
        echo "The base branch is: ${{ github.base_ref }}"
