name: Manual Trigger Workflow

# Configure Manual Trigger
on:
  workflow_dispatch:
    inputs:
      source-branch:
        description: 'Name of the source branch'
        required: true
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Merge source branch into Target branch
      run: |
        GITHUB_REF=${{ github.ref }}
        BRANCH_NAME=${GITHUB_REF##*/}
        echo ${BRANCH_NAME}
        echo ${{ inputs.source-branch }}
