name: sfdx-validation-on-PR
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  pull_request:
    types:
      - opened
      - reopened
    branches:
      - dev
jobs:
  sfdx-validation:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout scm
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install jq
        run: |
          sudo apt install -y jq
          jq --version
      - name: Install node js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: |
          node --version
          npm --version
      - name: Install salesforce cli
        run: |
          npm install -g @salesforce/cli
          sf -v
      - name: Authorize with salesforce org
        run: |
          echo "${{ secrets.ENCODED_SERVER_KEY }}" | base64 -d > server.key
          sf auth:jwt:grant --instance-url ${{ env.SF_INSTANCE_URL }} --username ${{ env.SF_USERNAME }} --client-id ${{ env.SF_CONSUMER_KEY }} --jwt-key-file server.key
      - name: Run all local apex tests
        run: sf apex run test --test-level RunLocalTests --target-org ${{ env.SF_USERNAME }} --code-coverage --output-dir . --result-format human --wait 240