name: sfdx-validation-on-PR
run-name: ${{ github.actor }} is learning GitHub Actions
on: 
  pull_request:
    types:
      - opened
      - reopened
    branches:
      - dev
jobs:
  sfdx-validation:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout scm
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install jq
        run: |
          sudo apt install -y jq
          jq --version
      - name: Get PR number and PR description
        run: |
          set -x
          PR_NUMBER=${{ github.event.number }}
          PR_DESCRIPTION=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          "https://api.github.com/repos/${{ github.repository }}/pulls/${PR_NUMBER}" \
          | jq -r '.body')
          echo "PR Description: $PR_DESCRIPTION"
          PROCESSED_DESCRIPTION=$(echo "${PR_DESCRIPTION}" | tr -d '\r\n' | sed '/^$/d' | awk '{$1=$1};1')
          echo "Trimmed PR Description: ${PROCESSED_DESCRIPTION}"
          chmod +x .github/workflows/processTestClass.sh
          output=$(.github/workflows/processTestClass.sh "$PROCESSED_DESCRIPTION")
          echo "Output: $output"
          TestLevel=$(echo "$output" | awk 'NR==1')
          TestClasses=$(echo "$output" | awk 'NR==2')         
          echo "1Test Level: $TestLevel"
          echo "1Test Classes: $TestClasses"
          echo "TestLevel=${TestLevel}" >> $GITHUB_ENV
          echo "TestClasses='${TestClasses}'" >> $GITHUB_ENV
          source $GITHUB_ENV
          echo "2Test Level: $TestLevel"
          echo "2Test Classes: $TestClasses"
      - name: Use the captured values
        run: |
          echo "Do something with Test Level: ${{ env.TestLevel }}"
          echo "Do something with TestClasses: ${{ env.TestClasses }}"
      - name: Install node js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - run: |
          node --version
          npm --version
      - name: Install salesforce cli
        run: |
          wget https://developer.salesforce.com/media/salesforce-cli/sf/channels/stable/sf-linux-x64.tar.xz
          echo "present working directory is -----------------------"
          pwd
          mkdir -p ~/cli/sf
          tar xJf sf-linux-x64.tar.xz -C ~/cli/sf --strip-components 1
          echo "~/cli/sf/bin" >> $GITHUB_PATH
          ~/cli/sf/bin/sf --version 
      - name: Authorize with salesforce org
        run: |
          echo "${{ secrets.SERVER_KEY_FILE }}" > server.key
          sf auth:jwt:grant --instance-url https://login.salesforce.com/ --username pratimamaiti@nagarro.com --client-id 3MVG9pRzvMkjMb6kNn45Qi9K2FLiCMPaUlgi9jHEcgHqZSVlMWwhpHmn8T4VINYFTBYElbS0KV0GyvDfS2MOg --jwt-key-file server.key
      - name: Install sfdx git delta plugin
        run: echo y | sf plugins:install sfdx-git-delta
      - name: Display checked-out branch
        run: |
          echo "Checked-out branch: ${{ github.ref }}"
      - name: Create delta package for deployment
        run: |
          mkdir Delta
          git branch
          sf sgd:source:delta --to HEAD --from HEAD~1 --output Delta
          ls
          cat Delta/destructiveChanges/destructiveChanges.xml
          cat Delta/package/package.xml
      - name: Validation against salesforce
        run: |
          set -x
          TestClassestoBeUsed=$(echo "$TestClasses" | sed "s/'//g")
          echo "Test classes to be passed: $TestClassestoBeUsed"
          sf project deploy start --manifest Delta/package/package.xml --target-org pratimamaiti@nagarro.com --test-level RunSpecifiedTests --tests $TestClassestoBeUsed --wait 20 --dry-run --json
